function mlbVariables(game) {
    return {
        gameId: game.id,
        attendance: game.competitions[0].attendance,
        awayAwayRecord: game.competitions[0].competitors[1].records[2]?.summary,
        awayLogo: game.competitions[0].competitors[1].team.logo,
        awayOdds: game.competitions[0].odds?.[0]?.awayTeamOdds?.moneyLine || "",
        awayOverallRecord: game.competitions[0].competitors[1].records[0]?.summary,
        awayRecord: game.competitions[0].competitors[1].records[0].summary,
        awayScore: game.competitions[0].competitors[1].score,
        awayTeam: game.competitions[0].competitors[1].team.displayName,
        awayTeamId: game.competitions[0].competitors[1].team.id,
        battingTeamId: game.competitions[0].situation?.batter?.athlete?.team?.id,
        balls: game.competitions[0].situation?.balls ?? 0,
        currentBatter: game.competitions[0].situation?.batter?.athlete?.displayName || "",
        currentBatterId: game.competitions[0].situation?.batter?.athlete?.team?.id || "",
        currentPitcher: game.competitions[0].situation?.pitcher?.athlete?.displayName || "",
        currentWeather: game.weather?.conditionId || "",
        dueUp1: game.competitions[0].situation?.dueUp?.[0]?.athlete?.fullName,
        dueUp2: game.competitions[0].situation?.dueUp?.[1]?.athlete?.fullName,
        dueUp3: game.competitions[0].situation?.dueUp?.[2]?.athlete?.fullName,
        futureWeather: game.weather?.displayValue || "",
        gameShortDetail: game.status.type.shortDetail,
        gameStatus: game.status.type.description,
        gameSummary: game.competitions[0].headlines?.[0]?.shortLinkText || "",
        homeAwayRecord: game.competitions[0].competitors[0].records[2]?.summary,
        homeHomeRecord: game.competitions[0].competitors[0].records[1]?.summary,
        homeLogo: game.competitions[0].competitors[0].team.logo,
        homeOdds: game.competitions[0].odds?.[0]?.homeTeamOdds?.moneyLine || "",
        homeOverallRecord: game.competitions[0].competitors[0].records[0]?.summary,
        homeRecord: game.competitions[0].competitors[0].records[0].summary,
        homeScore: game.competitions[0].competitors[0].score,
        homeTeam: game.competitions[0].competitors[0].team.displayName,
        homeTeamId: game.competitions[0].competitors[0].team.id,
        inning: game.status.type.detail,
        inningStatus: game.competitions[0].situation?.lastPlay?.type.text || "",
        lastPlay: game.competitions[0].situation?.lastPlay?.text || "",
        onFirst: game.competitions[0].situation?.onFirst ?? false,
        onSecond: game.competitions[0].situation?.onSecond ?? false,
        onThird: game.competitions[0].situation?.onThird ?? false,
        outs: game.competitions[0].outsText,
        overUnder: game.competitions[0]?.odds?.[0]?.overUnder || "",
        probableAwayStarter: game.competitions[0].competitors[1].probables?.[0]?.athlete?.displayName || "Undecided",
        probableAwayStarterStats: game.competitions[0].competitors[1].probables?.[0]?.record || "",
        probableHomeStarter: game.competitions[0].competitors[0].probables?.[0]?.athlete?.displayName || "Undecided",
        probableHomeStarterStats: game.competitions[0].competitors[0].probables?.[0]?.record || "",
        shortAwayTeam: game.competitions[0].competitors[1].team.abbreviation,
        shortHomeTeam: game.competitions[0].competitors[0].team.abbreviation,
        strikes: game.competitions[0].situation?.strikes ?? 0,
        temperature: game.weather?.temperature || "",
        venue: game.competitions[0].venue.fullName
    };
}

export default mlbVariables;
